[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2021"

[dependencies]
colorsys = "0.6.7"
image = "0.24.5"
num = "0.4.0"
rayon = "1.7.0"
sdl2 = "0.35.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

